Source/DK.Web/Controllers/KiemKeController.cs
using DK.Application;
using DK.Application.Models;
using DK.Application.Repositories;
using DK.Web.Core;
using MongoDB.Driver;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.IO;
using MediaDevices;
using Newtonsoft.Json;

namespace DK.Web.Controllers
{
    [Authorize]
    public class KiemKeController : BaseController
    {
        private readonly string HtmlFolder = System.Web.HttpContext.Current.Server.MapPath("~/Html\\");
        private readonly ITaiSanRepository _taiSanRepository;
        private readonly ITypeRepository _typeRepository;
        private readonly IKiemKeRepository _kiemKeRepository;
        private readonly ITaiSanService _taiSanService;
        public KiemKeController(ITaiSanRepository taiSanRepository, ITypeRepository typeRepository, IKiemKeRepository kiemKeRepository, ITaiSanService taiSanService)
        {
            _taiSanRepository = taiSanRepository;
            _typeRepository = typeRepository;
            _kiemKeRepository = kiemKeRepository;
            _taiSanService = taiSanService;
        }

        // GET: Category
        public ActionResult Index(DefaultSearchModel pagerInfo)
        {
            var list = _typeRepository.Find(m => m.Name == TypeConstant.KiemKe);
            var pager = new Pager(list.Count(), pagerInfo.PageIndex, pagerInfo.PageSize);

            var result = new PagerViewModel
            {
                BaseUrl = Url.Action("Index", new { pagerInfo.PageSize }),
                Items = list.OrderByDescending(m => m.Created).Skip((pager.CurrentPage - 1) * pager.PageSize).Take(pager.PageSize).ToList(),
                Pager = pager
            };

            return View(result);
        }

        public async Task<ActionResult> Detail(Guid id, DefaultSearchModel pagerInfo)
        {
            var kiemke = await _typeRepository.GetAsync(id);
            ViewBag.KiemKe = kiemke;

            var list = _kiemKeRepository.Find(m => m.KiemKeId == kiemke.Id).OrderBy(m => m.Number);
            var pager = new Pager(list.Count(), pagerInfo.PageIndex, pagerInfo.PageSize);

            var result = new PagerViewModel
            {
                BaseUrl = Url.Action("Detail", new { id, pagerInfo.PageSize }),
                Items = list.Skip((pager.CurrentPage - 1) * pager.PageSize).Take(pager.PageSize).ToList(),
                Pager = pager
            };

            return View(result);
        }

        public ActionResult Merge(List<Guid> kiemKeIds, string name, string returnUrl)
        {
            if (!kiemKeIds.Any()) return Redirect(returnUrl);
            var kiemKes = new List<KiemKe>();
            foreach (var item in kiemKeIds)
            {
                kiemKes.AddRange(_kiemKeRepository.Find(m => m.KiemKeId == item));
            }
            var kiemKeLst = new List<KiemKe>();
            var kkType = _typeRepository.Add(new Application.Models.Type { Title = name, Name = TypeConstant.KiemKe, CreatedBy = User.Identity.Name });
            foreach (var item in kiemKes)
            {
                var kk = kiemKeLst.FirstOrDefault(m => m.Code == item.Code);
                if (kk == null)
                {
                    kiemKeLst.Add(item);
                    item.KiemKeId = kkType.Id;
                }
                else if (kk.SoLuongKiemKe < item.SoLuongKiemKe)
                {
                    var index = kiemKeLst.FindIndex(m => m.Id == kk.Id);
                    kiemKeLst[index].SoLuongKiemKe = item.SoLuongKiemKe;
                }
            }
            foreach (var item in kiemKeIds)
            {
                _kiemKeRepository.DeleteMany(nameof(KiemKe.KiemKeId), item);
                _typeRepository.Delete(item);
            }
            _kiemKeRepository.AddRange(kiemKeLst);

            return Redirect(returnUrl);
        }

        public string PushData(Guid id)
        {
            try
            {
                var kiemKes = _kiemKeRepository.Find(m => m.KiemKeId == id);
                string output = JsonConvert.SerializeObject(kiemKes);
                var devices = MediaDevice.GetDevices();
                using (var device = devices.First())
                {
                    device.Connect();
                    var filename = $@"Bộ nhớ trong dùng chung\Download\kiem_ke.json";
                    using (StreamWriter w = new StreamWriter($"{HtmlFolder}KiemKe.json", false))
                    {
                        w.Write(output);
                    }
                    if (device.FileExists(filename)) device.DeleteFile(filename);
                    device.UploadFile($"{HtmlFolder}KiemKe.json", filename);
                    device.Disconnect();
                }

                return null;
            }
            catch (Exception e)
            {
                var message = e.Message;
                if (message?.Equals("Sequence contains no elements", StringComparison.OrdinalIgnoreCase) == true)
                    message = "Thiết bị kiếm kê chưa kết nối với máy chủ";
                return "Có lỗi khi xuất dữ liệu ra thiết bị. " + message;
            }
        }

        public string PullData(Guid id)
        {
            try
            {
                var type = _typeRepository.Get(id);
                var kiemKes = _kiemKeRepository.Find(m => m.KiemKeId == id).ToList();
                var devices = MediaDevice.GetDevices();
                using (var device = devices.First())
                {
                    device.Connect();
                    var filename = $@"Bộ nhớ trong dùng chung\Download\kiem_ke.json";
                    if (!device.FileExists(filename)) throw new Exception($"Không tìm thấy đợt kiểm kê '{type.Title}' từ thiết bị kiểm kê");
                    var serializer = new JsonSerializer();
                    var memorySteam = new MemoryStream();
                    device.DownloadFile(filename, $"{HtmlFolder}KiemKe.json");
                    var str = new StreamReader($"{HtmlFolder}KiemKe.json");
                    using (var jsonTextReader = new JsonTextReader(str))
                    {
                        var lstKiemKe = serializer.Deserialize<List<KiemKe>>(jsonTextReader);
                        foreach (var item in lstKiemKe)
                        {
                            var kk = kiemKes.FirstOrDefault(m => m.Code == item.Code);
                            if (kk != null && kk.SoLuongKiemKe != item.SoLuongKiemKe)
                            {
                                _kiemKeRepository.Set(item.Id, nameof(KiemKe.SoLuongKiemKe), item.SoLuongKiemKe);
                            }
                        }
                    }
                    memorySteam.Close();
                    str.Close();

                    device.Disconnect();
                }

                return null;
            }
            catch (Exception e)
            {
                var message = e.Message;
                if (message?.Equals("Sequence contains no elements", StringComparison.OrdinalIgnoreCase) == true)
                    message = "Thiết bị kiếm kê chưa kết nối với máy chủ";
                return "Có lỗi khi đọc dữ liệu từ thiết bị. " + message;
            }
        }

        public ActionResult NewOrEdit(Guid parentId, Guid? id = null, string returnUrl = "")
        {
            //CreateDropDownViewBag();
            KiemKe kiemKe = null;
            if (id.HasValue)
            {
                kiemKe = _kiemKeRepository.Get(id.Value);
            }

            if (kiemKe == null)
            {
                kiemKe = new KiemKe { KiemKeId = parentId };
            }

            return View(kiemKe);
        }

        [HttpPost]
        public ActionResult NewOrEdit(KiemKe kiemke, string returnUrl)
        {
            if (!ModelState.IsValid)
            {
                foreach (ModelState modelState in ViewData.ModelState.Values)
                {
                    foreach (ModelError error in modelState.Errors)
                    {
                    }
                }
                return View(kiemke);
            }

            var current = _kiemKeRepository.Get(kiemke.Id);
            if (current == null)
            {
                var existingCodes = _taiSanService.GetExistingCodes();
                var ts = new TaiSan() { Name = kiemke.Name };
                ts.GenerateCode(existingCodes);

                kiemke.Code = ts.Code;
                kiemke.CreatedBy = User.Identity.Name;
            }
            else
            {
                kiemke.CreatedBy = current.CreatedBy;
            }

            _kiemKeRepository.Upsert(kiemke);
            if (string.IsNullOrWhiteSpace(returnUrl)) return RedirectToAction(nameof(Detail), new { kiemke.KiemKeId }); else return Redirect(returnUrl);
        }

        [HttpPost]
        public async Task<ActionResult> Detail(Application.Models.Type model)
        {
            var kiemke = await _typeRepository.GetAsync(model.Id);
            kiemke.Title = model.Title;
            _typeRepository.Update(kiemke);

            return RedirectToAction("Detail", new { kiemke.Id });
        }

        public async Task<ActionResult> DeleteKiemKe(Guid id, string returnUrl)
        {
            var kiemke = await _kiemKeRepository.GetAsync(id);
            if (kiemke == null)
            {
                return NotFound();
            }

            returnUrl = string.IsNullOrEmpty(returnUrl) ? Url.Action(nameof(Detail), new { kiemke.KiemKeId }) : returnUrl;
            try
            {
                await _kiemKeRepository.DeleteAsync(id);
            }
            catch (Exception _)
            {

            }

            return Redirect(returnUrl);
        }

        public async Task<ActionResult> Delete(Guid id)
        {
            var kiemke = await _typeRepository.GetAsync(id);
            if (kiemke == null)
            {

Source/DK.Web/Views/Home/Dashboard.cshtml
@using DK.Application.Models
@model DK.Web.Models.DashboardModel
@{
    ViewBag.Title = "Tổng quan";
    var colors = new List<string>
{
        "bg-teal",
        "bg-danger",
        "bg-danger",
        "bg-warning",
        "bg-info",
        "bg-purple",
        "bg-teal",
        "bg-danger",
        "bg-danger",
        "bg-warning",
        "bg-info",
        "bg-purple"
    };
}

<style>
    .table {
        background-color: transparent;
    }

    .min-height {
        min-height: 478px;
    }
</style>

<div class="row row-sm">
    <div class="col-sm-6 col-xl-3">
        <div class="bg-teal rounded overflow-hidden">
            <div class="pd-25 d-flex align-items-center">
                <i class="ion ion-ios-checkmark-outline tx-60 lh-0 tx-white op-7"></i>
                <div class="mg-l-20">
                    <p class="tx-10 tx-spacing-1 tx-mont tx-medium tx-uppercase tx-white-8 mg-b-10">Tổng số đợt kiểm kê</p>
                    <p class="tx-24 tx-white tx-lato tx-bold mg-b-2 lh-1">@Model.TongSoDotKiemKe</p>
                    <span class="tx-11 tx-roboto tx-white-6"></span>
                </div>
            </div>
        </div>
    </div><!-- col-3 -->
    <div class="col-sm-6 col-xl-3 mg-t-20 mg-sm-t-0">
        <div class="bg-danger rounded overflow-hidden">
            <div class="pd-25 d-flex align-items-center">
                <i class="ion ion-bag tx-60 lh-0 tx-white op-7"></i>
                <div class="mg-l-20">
                    <p class="tx-10 tx-spacing-1 tx-mont tx-medium tx-uppercase tx-white-8 mg-b-10">Tổng số tài sản</p>
                    <p class="tx-24 tx-white tx-lato tx-bold mg-b-2 lh-1">@Model.TongSoTaiSan</p>
                    <span class="tx-11 tx-roboto tx-white-6"></span>
                </div>
            </div>
        </div>
    </div><!-- col-3 -->
    <div class="col-sm-6 col-xl-3 mg-t-20 mg-xl-t-0">
        <div class="bg-primary rounded overflow-hidden">
            <div class="pd-25 d-flex align-items-center">
                <i class="ion ion-model-s tx-60 lh-0 tx-white op-7"></i>
                <div class="mg-l-20">
                    <p class="tx-10 tx-spacing-1 tx-mont tx-medium tx-uppercase tx-white-8 mg-b-10">Tổng số xe</p>
                    <p class="tx-24 tx-white tx-lato tx-bold mg-b-2 lh-1">@Model.TongSoXe</p>
                    <span class="tx-11 tx-roboto tx-white-6"></span>
                </div>
            </div>
        </div>
    </div><!-- col-3 -->
    <div class="col-sm-6 col-xl-3 mg-t-20 mg-xl-t-0">
        <div class="bg-br-primary rounded overflow-hidden">
            <div class="pd-25 d-flex align-items-center">
                <i class="ion ion-social-usd-outline tx-60 lh-0 tx-white op-7"></i>
                <div class="mg-l-20">
                    <p class="tx-10 tx-spacing-1 tx-mont tx-medium tx-uppercase tx-white-8 mg-b-10">Tổng giá ban đầu</p>
                    <p class="tx-24 tx-white tx-lato tx-bold mg-b-2 lh-1">@Model.TongNguonKinhPhi.ToString("N0")</p>
                    <span class="tx-11 tx-roboto tx-white-6"></span>
                </div>
            </div>
        </div>
    </div><!-- col-3 -->
</div><!-- row -->

<div class="row row-sm mg-t-20">
    <div class="col-8">
        <div class="card bd-0 shadow-base pd-30 min-height">
            <div class="d-flex align-items-center justify-content-between mg-b-30">
                <div>
                    <h6 class="tx-13 tx-uppercase tx-inverse tx-semibold tx-spacing-1">Các đợt kiểm kê gần đây</h6>
                </div>
                <a href="/KiemKe/Index" class="btn btn-outline-info btn-oblong tx-11 tx-uppercase tx-mont tx-medium tx-spacing-1 pd-x-30 bd-2">Xem thêm</a>
            </div><!-- d-flex -->

            <table class="table table-valign-middle mg-b-0">
                <tbody>
                    @foreach (var item in Model.RecentKiemKes)
                    {
                        <tr>
                            <td>
                                <h6 class="tx-inverse tx-14 mg-b-0">
                                    <a href="@Url.Action("Detail", "KiemKe", new {item.Id })">@item.Title</a>
                                </h6>
                                <span class="tx-12">@item.CreatedBy</span>
                            </td>
                            <td>@item.Created.ToString("dd/MM/yyyy")</td>
                            <td class="pd-r-0-force tx-center"><a href="@Url.Action("Detail", "KiemKe", new {item.Id })" class="tx-gray-600"><i class="icon ion-link tx-18 lh-0"></i></a></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>

    </div><!-- col-9 -->
    <div class="col-4">
        <div class="card bd-0 shadow-base pd-30  min-height">
            <h6 class="tx-13 tx-uppercase tx-inverse tx-semibold tx-spacing-1">Danh mục (@ViewBag.Total)</h6>
            <br />
            @{
                var count = 0;
                foreach (var item in Model.DanhMucPercent)
                {
                    <label class="tx-12 tx-gray-600 mg-b-10">
                        <a href="@Url.Action("Index", "Category", new {Id = item.Key })">@item.Key (@Model.DanhMuc[item.Key])</a>
                    </label>
                    <div class="progress ht-5 mg-b-10">
                        <div class="progress-bar @colors[count] wd-@(item.Value)p" role="progressbar" aria-valuenow="@item.Value" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                    count++;
                }
            }
            <div class="mg-t-20 tx-13">
            </div>
        </div><!-- card -->
    </div><!-- col-3 -->
</div><!-- row -->

Source/DK.Web/Views/Home/Import.cshtml
@using DK.Web.Utilities
@using DK.Application.Models
@model DK.Web.Core.PagerViewModel
@{
    ViewBag.Title = "Import tài sản từ excel";
}

<div class="row mt-2">
    <div class="col-12">
        <div class="card shadow-base bd-0">
            @using (Html.BeginForm("Import", "Home", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
            <div class="form-horizontal mt-3">
                <div class="form-group">
                    <div class="col-md-10">
                        <input type="file" name="taisan" id="taisan" required />
                    </div>

                </div>
                <div class="ml-3 text-danger">@ViewBag.Error</div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button type="submit" class="btn btn-primary"><i class="fa fa-upload"> </i> Import</button>
                        <a href="javascript:history.back()" class="btn btn-default"><i class="fa fa-arrow-left"></i> Quay lại</a>
                    </div>
                </div>
            </div>
            }
        </div>
    </div>
</div>

Source/DK.Web/Views/Home/ImportUpdate.cshtml
@using DK.Web.Utilities
@using DK.Application.Models
@model DK.Web.Core.PagerViewModel
@{
    ViewBag.Title = "Chỉnh sửa tài sản từ excel";
}

<div class="row mt-2">
    <div class="col-12">
        <div class="card shadow-base bd-0">
            @using (Html.BeginForm("ImportUpdate", "Home", new { returnUrl = Request.Params["returnUrl"] }, FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
            <div class="form-horizontal mt-3">
                <div class="form-group">
                    <div class="col-md-10">
                        <input type="file" name="taisan" id="taisan" required />
                    </div>

                </div>
                <div class="ml-3 text-danger">@ViewBag.Error</div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button type="submit" class="btn btn-primary"><i class="fa fa-upload"> </i> Import</button>
                        <a href="@Request.Params["returnUrl"]" class="btn btn-default"><i class="fa fa-arrow-left"></i> Quay lại</a>
                    </div>
                </div>
            </div>
            }
        </div>
    </div>
</div>

Source/DK.Web/Views/Home/Index.cshtml
@using DK.Web.Utilities
@using DK.Application.Models
@model DK.Web.Core.PagerViewModel
@{
    ViewBag.Title = "Danh sách tài sản";
    var searchModel = ViewBag.SearchModel as DK.Application.Models.TaiSanSearchModel;
    var canManage = DK.Application.Models.RoleList.GetAll().Any(User.IsInRole);
}

@section styles {
    <link href="@Url.Content("~/Content/asset-management.css")" rel="stylesheet">
}

@section Button {
    @if (canManage)
    {
        <a href="@Url.Action("ImportUpdate", new { returnUrl = Request.RawUrl})" class="btn btn-info btn-sm pull-right"><i class="fa fa-upload"></i> Import chỉnh sửa</a>
    }
}

<div class="card mt-2 mb-2 shadow-base" id="searchBox">
    <div class="card-body pb-0">
        @Html.Partial("_SearchForm", searchModel)
    </div>
</div>

<div class="row mt-2">
    <div class="col-12">
        <form method="post">
            <div class="card shadow-base bd-0">
                <div class="table-responsive">
                    @Html.Partial("_Table", Model.Items)
                </div>
            </div>
            @Html.Partial("_PagerPartial", Model)
        </form>

        <div class="d-none">
            <form action="/Home/DeleteTaiSan" method="post" id="form-delete">
                <input type="hidden" name="isApproved" value="true" />
                <div class="form-content">
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    <link href="@Url.Content("~/Content/lib/select2/css/select2-bootstrap.min.css")" rel="stylesheet">
    <script src="~/Content/lib/select2/js/select2.min.js"></script>
    <script src="~/Scripts/common.js"></script>
    <script src="~/Scripts/asset-management.js"></script>
}

Source/DK.Web/Views/Home/NewOrEditAsset.cshtml
@using DK.Application.Models
@model TaiSan
@{
    ViewBag.Title = Model.Id != Guid.Empty ? "Chỉnh sửa tài sản" : "Thêm mới tài sản";
    var canManage = DK.Application.Models.RoleList.GetAll().Any(User.IsInRole);
    ViewBag.ParentId = Model.Id;
}

<style>
    .search-item {
        margin-bottom: 10px;
    }

        .search-item label {
            margin-bottom: 0;
        }

    .bootstrap-tagsinput {
        width: 100%;
        padding: 0px 6px 5px 6px !important;
    }

    hr {
        margin-top: 5px;
        margin-bottom: 5px;
    }

    @@media (min-width: 1200px) {
        .modal-xl {
            max-width: 1140px;
        }
    }
</style>

@using (Html.BeginForm(null, null, FormMethod.Post, new { role = "form", onsubmit = "removeCurrencySeparators()" }))
{
    if (canManage || !Model.IsApproved)
    {
        <button class="btn btn-sm bd bg-primary tx-white pointer"><i class="fa fa-save"></i> Lưu lại</button>
    }
    <a class="btn btn-sm bd pointer bg-white" href="@Request.Params["returnUrl"]"><i class="fa fa-arrow-left"></i> Quay lại</a>
    <div class="card mt-2 mb-2 shadow-base">
        <div class="card-body">
            @Html.Partial("_NewOrEditAssetForm", Model)
        </div>
    </div>
    if (canManage || !Model.IsApproved)
    {
        <button class="btn btn-sm bd bg-primary tx-white pointer"><i class="fa fa-save"></i> Lưu lại</button>
    }
    <a class="btn btn-sm bd pointer bg-white" href="@Request.Params["returnUrl"]"><i class="fa fa-arrow-left"></i> Quay lại</a>


}
@if (Model.Id != Guid.Empty)
{
    <h4 class="mt-3">
        Danh sách tài sản con
    </h4>
    if (canManage || !Model.IsApproved)
    {
        <div class="mb-1">
            <a href="@Url.Action("NewOrEditChildAsset", "Home", new { parentId = Model.Id, Code = "", returnUrl = Request.RawUrl })" class="btn btn-primary btn-sm mr-1"><i class="fa fa-plus"></i> Thêm</a>
        </div>
    }
    <div class="card shadow-base mb-2 bd-0" id="children-asset">
        <div class="table-responsive">
            @Html.Partial("_TableChild", Model.Children)
        </div>
    </div>
}

@section Scripts {
    <link href="@Url.Content("~/Content/lib/select2/css/select2-bootstrap.min.css")" rel="stylesheet">
    <link href="~/Content/lib/bootstrap-tagsinput/bootstrap-tagsinput.css" rel="stylesheet" />
    <script src="~/Scripts/jquery.maskMoney.min.js"></script>
    <script src="~/Content/lib/select2/js/select2.min.js"></script>
    <script src="~/Content/lib/bootstrap-tagsinput/bootstrap-tagsinput.js"></script>
    <script src="~/Scripts/common.js"></script>
    <script>
        $(document).ready(function () {
            var activeClass = "@(Model.IsApproved ? "asset-approved": "asset-unapproved")";
            reActiveMenu(activeClass);
        });

        function reActiveMenu(activeClass) {
            $("#LeftMenu a.asset").removeClass('active');
            $("#LeftMenu a." + activeClass).addClass('active');
        }
        function removeTaiSanChild() {
            return confirm("Bạn có chắc muốn xóa?");
        }
    </script>
}

Source/DK.Web/Views/Home/NewOrEditChildAsset.cshtml
@using DK.Application.Models
@model TaiSan
@{
    ViewBag.Title = !string.IsNullOrEmpty(Model.Code) ? "Chỉnh sửa tài sản con" : "Thêm mới tài sản con";
    var canManage = DK.Application.Models.RoleList.GetAll().Any(User.IsInRole);
}

<style>
    .search-item {
        margin-bottom: 10px;
    }

        .search-item label {
            margin-bottom: 0;
        }

    @@media (min-width: 1200px) {
        .modal-xl {
            max-width: 1140px;
        }
    }
</style>

@using (Html.BeginForm(null, null, FormMethod.Post, new { role = "form" }))
{
    <div class="card mt-2 mb-2 shadow-base">
        <div class="card-body">
            @Html.Hidden("returnUrl", Request.Params["returnUrl"])
            @Html.HiddenFor(m => m.ParentId)
            @Html.HiddenFor(m => m.Id)
            @Html.HiddenFor(m => m.IsApproved)
            @Html.ValidationSummary(true)
            <div class="row mb-2">
                <div class="col-md-4 col-sm-6 search-item">
                    @Html.LabelFor(m => m.Code)
                    @Html.TextBoxFor(m => m.Code, new { Class = "form-control form-control-sm", ReadOnly = "true" })
                </div>
                <div class="col-md-4 col-sm-6 search-item">
                    @Html.LabelFor(m => m.Name)
                    @Html.TextBoxFor(m => m.Name, new { Class = "form-control form-control-sm" })
                </div>
                <div class="col-md-4 col-sm-6 search-item">
                    @Html.LabelFor(m => m.NhanHieu)
                    @Html.TextBoxFor(m => m.NhanHieu, new { Class = "form-control form-control-sm" })
                </div>
                <div class="col-md-4 col-sm-6 search-item">
                    @Html.LabelFor(m => m.Serial)
                    @Html.TextBoxFor(m => m.Serial, new { Class = "form-control form-control-sm", placeholder = "Số khung/Số máy" })
                </div>
                <div class="col-md-4 col-sm-6 search-item">
                    @Html.LabelFor(m => m.XuatXu)
                    @Html.TextBoxFor(m => m.XuatXu, new { Class = "form-control form-control-sm" })
                </div>
                <div class="col-md-4 col-sm-6 search-item">
                    @Html.LabelFor(m => m.NamSanXuat)
                    @Html.TextBoxFor(m => m.NamSanXuat, new { type = "number", Class = "form-control form-control-sm" })
                </div>
                <div class="col-md-4 col-sm-6 search-item">
                    @Html.LabelFor(m => m.NamSuDung)
                    @Html.TextBoxFor(m => m.NamSuDung, new { type = "number", Class = "form-control form-control-sm" })
                </div>
                <div class="col-md-4 col-sm-6 search-item">
                    @Html.LabelFor(m => m.SoLuong)
                    @Html.TextBoxFor(m => m.SoLuong, new { type = "number", Class = "form-control form-control-sm" })
                </div>
                <div class="col-md-4 col-sm-6 search-item">
                    @Html.LabelFor(m => m.KhoiLuong)
                    @Html.TextBoxFor(m => m.KhoiLuong, new { type = "number", Class = "form-control form-control-sm" })
                </div>
                <div class="col-md-4 col-sm-6 search-item">
                    @Html.LabelFor(m => m.ChatLuong)
                    @Html.BuildDrodownList("ChatLuong", ViewBag.ChatLuong as IEnumerable<string>, Model.ChatLuong)
                </div>
            </div>
        </div>
    </div>
    <button class="btn btn-sm bd bg-primary tx-white"><i class="fa fa-save"></i> Lưu lại</button>
    <a class="btn btn-sm bd pointer bg-white" onclick="window.history.back()"><i class="fa fa-arrow-left"></i> Quay lại</a>
}


@section Scripts {
    <link href="@Url.Content("~/Content/lib/select2/css/select2-bootstrap.min.css")" rel="stylesheet">
    <script src="~/Content/lib/select2/js/select2.min.js"></script>
    <script src="~/Scripts/common.js"></script>
    <script>
        $(document).ready(function () {
            var activeClass = "@(Model.IsApproved ? "asset-approved": "asset-unapproved")";
            reActiveMenu(activeClass);
        });

        function reActiveMenu(activeClass) {
            $("#LeftMenu a.asset").removeClass('active');
            $("#LeftMenu a." + activeClass).addClass('active');
        }
    </script>
}